---
version: '3.3'
services:

  application:
    build: .
    ports: ['8080:8080']
    links :
      - influxdb:influxdb
    depends_on: ['influxdb']

  influxdb:
    image: influxdb:latest
    ports: ['8086:8086']
